### ISSUE TITLE
could plot_ss support the formula interface?

### ISSUE THREAD

**Issue by beanumber** [andrewpbray/oilabs#10]
This seems like it wouldn't be that hard to do. Could we write a `plot_ss.formula()` method that takes a `formula` as its first argument and a data frame as its `data` argument?

**Comment by andrewpbray** [comment]
I think that'd make sense for the labs that use `lattice` graphics. For the `ggplot2` ones, we're using `qplot()`, which goes

```{r}
qplot(x = height, y = weight, data = cdc, geom = "point")
```
