### ISSUE TITLE
make calc_streak use rle() instead of custom code?

### ISSUE THREAD

**Issue by beanumber** [andrewpbray/oilabs#21]
This should be a one-liner but it's not due to the way we're interpreting streaks of length 0. 

Perhaps someone more clever than me can figure this out.

**Comment by rudeboybert** [comment]
FWIW an astute student of mine pointed out that the independent shooter streak lengths are `X-1`, where `X` is a geometric random variable with `p=0.55` (i.e. prob of a miss)!

**Comment by andrewpbray** [comment]
This would work, right?

```{r}
x <- rev(rep(6:10, 1:5))
rle(x)$lengths - 1
```
The only downside that I see is that "run length encoding" is a less informative name than "calc streak". What would be the advantage of getting rid of `calc_streak()`?

**Comment by beanumber** [comment]
Unfortunately I think it's trickier than that. The example you have:
```
sequence <- c("H", "H", "M", "H", "M", "M", "H", "H", "H")
calc_streak(sequence)
[1] 2 1 0 3
```
But 
```
rle(sequence)$lengths
[1] 2 1 1 2 3
```
includes the runs of both Hs and Ms. So you really want to filter the results of `rle` for only those runs of Hs. But even that isn't right because we are saying that two Ms in a row is a streak of length 0. 

Anyway, the idea was just to replace the custom code *inside* `calc_streak()` with an appeal to `rle` -- not to remove `calc_streak()` entirely. Maybe it's not worth it. Or maybe we should redefine our definition of runs to be in line with those used by `rle`.

**Comment by andrewpbray** [comment]
Ah, right.

Changing `calc_streak()` doesn't seem worth it to me. The proportion of students that look inside the functions $\approx$ 0.
