### ISSUE TITLE
Error in FUN(X[[1L]], ...)

### ISSUE THREAD

**Issue by ismayc** [andrewpbray/oilabs#26]
In trying to run the `inference` function on to compare the two mean sleep hours for whether or not someone has a job, I am receiving the following error.

```
> inference(y = d$sleep_hrs, 
+           x = d$job, 
+           est = "mean", 
+           type = "ht", 
+           null = 0, 
+           alternative = "twosided", 
+           method = "theoretical")
Response variable: numerical, Explanatory variable: categorical
Difference between two means
Summary statistics:
n_no = 12, mean_no = 7.2083, 
Error in FUN(X[[1L]], ...) : could not find function "FUN"

```

I believe the error occurs in the following code of the `inference` function.   It looks like it doesn't find the `sd` function.

```
 # summary statistics and eda plots
            cat("Summary statistics:\n")
            if (est == "mean") {
                for (i in 1:x_levels) {
                  cat("n_", names(by(y, x, length))[i], " = ", by(y, x, length)[i], ", ", sep = "")
                  cat("mean_", names(by(y, x, mean))[i], " = ", round(by(y, x, mean)[i], 4), ", ", 
                    sep = "")
                  cat("sd_", names(by(y, x, sd))[i], " = ", round(by(y, x, sd)[i], 4), "\n", sep = "")
                }
```

**Comment by mine-cetinkaya-rundel** [comment]
This is likely happening because in your environment there is a variable called `sd`. Can you check if this is the case?

**Comment by ismayc** [comment]
Thanks, Mine!  I was helping one of Andrew's students and completely overlooked their declaration of `sd` earlier in the file.  After changing that, the error went away and their document knit.
